<?php
     $version = '2025.01';
?>
<!DOCTYPE html>
<html lang="ta">
<?php include '../header.php'; ?>

<center>
<body>
<?php include '../menu.php'; ?>

<img src="../assets/main-head.gif">
</center>
<center><img src="../assets/54-1.gif"border=0></center>
<pre>
<center>
<a href="../html/kdic1.php?v=<?php echo $version; ?>"><img src="../assets/k1.gif"border=0>
<a href="../html/kdic2.php?v=<?php echo $version; ?>"><img src="../assets/k2.gif"border=0>
<a href="../html/kdic3.php?v=<?php echo $version; ?>"><img src="../assets/k3.gif"border=0>
<a href="../html/kdic4.php?v=<?php echo $version; ?>"><img src="../assets/k4.gif"border=0>
<a href="../html/kdic5.php?v=<?php echo $version; ?>"><img src="../assets/k5.gif"border=0>
<a href="../html/kdic6.php?v=<?php echo $version; ?>"><img src="../assets/k6.gif"border=0>
<a href="../html/kdic7.php?v=<?php echo $version; ?>"><img src="../assets/k7.gif"border=0>
<a href="../html/kdic8.php?v=<?php echo $version; ?>"><img src="../assets/k8.gif"border=0>
<a href="../html/kdic9.php?v=<?php echo $version; ?>"><img src="../assets/k9.gif"border=0>
<a href="../html/kdic10.php?v=<?php echo $version; ?>"><img src="../assets/k10.gif"border=0>
<a href="../html/kdic11.php?v=<?php echo $version; ?>"><img src="../assets/k11.gif"border=0>
<a href="../html/kdic12.php?v=<?php echo $version; ?>"><img src="../assets/k12.gif"border=0>
<a href="../html/kdic13.php?v=<?php echo $version; ?>"><img src="../assets/k13.gif"border=0>
<a href="../html/kdic14.php?v=<?php echo $version; ?>"><img src="../assets/k14.gif"border=0>
<a href="../html/kdic15.php?v=<?php echo $version; ?>"><img src="../assets/k15.gif"border=0>
<a href="../html/kdic16.php?v=<?php echo $version; ?>"><img src="../assets/k16.gif"border=0>
<a href="../html/kdic17.php?v=<?php echo $version; ?>"><img src="../assets/k17.gif"border=0>
<a href="../html/kdic18.php?v=<?php echo $version; ?>"><img src="../assets/k18.gif"border=0>
<a href="../html/kdic19.php?v=<?php echo $version; ?>"><img src="../assets/k19.gif"border=0>
<a href="../html/kdic20.php?v=<?php echo $version; ?>"><img src="../assets/k20.gif"border=0>
<a href="../html/kdic21.php?v=<?php echo $version; ?>"><img src="../assets/k21.gif"border=0>
<a href="../html/kdic22.php?v=<?php echo $version; ?>"><img src="../assets/k22.gif"border=0>
<a href="../html/kdic23.php?v=<?php echo $version; ?>"><img src="../assets/k23.gif"border=0>
<a href="../html/kdic24.php?v=<?php echo $version; ?>"><img src="../assets/k24.gif"border=0>
<a href="../html/kdic25.php?v=<?php echo $version; ?>"><img src="../assets/k25.gif"border=0>
<a href="../html/kdic26.php?v=<?php echo $version; ?>"><img src="../assets/k26.gif"border=0>
<a href="../html/kdic27.php?v=<?php echo $version; ?>"><img src="../assets/k27.gif"border=0>
<a href="../html/kdic28.php?v=<?php echo $version; ?>"><img src="../assets/k28.gif"border=0>
<a href="../html/kdic29.php?v=<?php echo $version; ?>"><img src="../assets/k29.gif"border=0>
<a href="../html/kdic30.php?v=<?php echo $version; ?>"><img src="../assets/k30.gif"border=0>
<a href="../html/kdic31.php?v=<?php echo $version; ?>"><img src="../assets/k31.gif"border=0>
<a href="../html/kdic32.php?v=<?php echo $version; ?>"><img src="../assets/k32.gif"border=0>
<a href="../html/kdic33.php?v=<?php echo $version; ?>"><img src="../assets/k33.gif"border=0>
<a href="../html/kdic34.php?v=<?php echo $version; ?>"><img src="../assets/k34.gif"border=0>
<a href="../html/kdic35.php?v=<?php echo $version; ?>"><img src="../assets/k35.gif"border=0>
<a href="../html/kdic36.php?v=<?php echo $version; ?>"><img src="../assets/k36.gif"border=0>
<a href="../html/kdic37.php?v=<?php echo $version; ?>"><img src="../assets/k37.gif"border=0>
<a href="../html/kdic38.php?v=<?php echo $version; ?>"><img src="../assets/k38.gif"border=0>
<a href="../html/kdic39.php?v=<?php echo $version; ?>"><img src="../assets/k39.gif"border=0>
<a href="../html/kdic40.php?v=<?php echo $version; ?>"><img src="../assets/k40.gif"border=0>
<a href="../html/kdic41.php?v=<?php echo $version; ?>"><img src="../assets/k41.gif"border=0>
<a href="../html/kdic42.php?v=<?php echo $version; ?>"><img src="../assets/k42.gif"border=0>
<a href="../html/kdic43.php?v=<?php echo $version; ?>"><img src="../assets/k43.gif"border=0>
<a href="../html/kdic44.php?v=<?php echo $version; ?>"><img src="../assets/k44.gif"border=0>
<a href="../html/kdic45.php?v=<?php echo $version; ?>"><img src="../assets/k45.gif"border=0>
<a href="../html/kdic46.php?v=<?php echo $version; ?>"><img src="../assets/k46.gif"border=0>
<a href="../html/kdic47.php?v=<?php echo $version; ?>"><img src="../assets/k47.gif"border=0>
<a href="../html/kdic48.php?v=<?php echo $version; ?>"><img src="../assets/k48.gif"border=0>
<a href="../html/kdic49.php?v=<?php echo $version; ?>"><img src="../assets/k49.gif"border=0>
<a href="../html/kdic50.php?v=<?php echo $version; ?>"><img src="../assets/k50.gif"border=0>
<a href="../html/kdic51.php?v=<?php echo $version; ?>"><img src="../assets/k51.gif"border=0>
<a href="../html/kdic52.php?v=<?php echo $version; ?>"><img src="../assets/k52.gif"border=0>
<a href="../html/kdic53.php?v=<?php echo $version; ?>"><img src="../assets/k53.gif"border=0>
<a href="../html/kdic54.php?v=<?php echo $version; ?>"><img src="../assets/k54.gif"border=0>
<a href="../html/kdic55.php?v=<?php echo $version; ?>"><img src="../assets/k55.gif"border=0>
<a href="../html/kdic56.php?v=<?php echo $version; ?>"><img src="../assets/k56.gif"border=0>
<a href="../html/kdic57.php?v=<?php echo $version; ?>"><img src="../assets/k57.gif"border=0>
<a href="../html/kdic58.php?v=<?php echo $version; ?>"><img src="../assets/k58.gif"border=0>
<a href="../html/kdic59.php?v=<?php echo $version; ?>"><img src="../assets/k59.gif"border=0>
<a href="../html/kdic60.php?v=<?php echo $version; ?>"><img src="../assets/k60.gif"border=0>
<a href="../html/kdic61.php?v=<?php echo $version; ?>"><img src="../assets/k61.gif"border=0>
<a href="../html/kdic62.php?v=<?php echo $version; ?>"><img src="../assets/k62.gif"border=0>
<a href="../html/kdic63.php?v=<?php echo $version; ?>"><img src="../assets/k63.gif"border=0>
<a href="../html/kdic64.php?v=<?php echo $version; ?>"><img src="../assets/k64.gif"border=0>
<a href="../html/kdic65.php?v=<?php echo $version; ?>"><img src="../assets/k65.gif"border=0>
<a href="../html/kdic66.php?v=<?php echo $version; ?>"><img src="../assets/k66.gif"border=0>
<a href="../html/kdic67.php?v=<?php echo $version; ?>"><img src="../assets/k67.gif"border=0>
<a href="../html/kdic68.php?v=<?php echo $version; ?>"><img src="../assets/k68.gif"border=0>
<a href="../html/kdic69.php?v=<?php echo $version; ?>"><img src="../assets/k69.gif"border=0>
<a href="../html/kdic70.php?v=<?php echo $version; ?>"><img src="../assets/k70.gif"border=0>
<a href="../html/kdic71.php?v=<?php echo $version; ?>"><img src="../assets/k71.gif"border=0>
<a href="../html/kdic72.php?v=<?php echo $version; ?>"><img src="../assets/k72.gif"border=0>
<a href="../html/kdic73.php?v=<?php echo $version; ?>"><img src="../assets/k73.gif"border=0>
<a href="../html/kdic74.php?v=<?php echo $version; ?>"><img src="../assets/k74.gif"border=0>
<a href="../html/kdic75.php?v=<?php echo $version; ?>"><img src="../assets/k75.gif"border=0>
<a href="../html/kdic76.php?v=<?php echo $version; ?>"><img src="../assets/k76.gif"border=0>
<a href="../html/kdic77.php?v=<?php echo $version; ?>"><img src="../assets/k77.gif"border=0>
<a href="../html/kdic78.php?v=<?php echo $version; ?>"><img src="../assets/k78.gif"border=0>
<a href="../html/kdic79.php?v=<?php echo $version; ?>"><img src="../assets/k79.gif"border=0>
<a href="../html/kdic80.php?v=<?php echo $version; ?>"><img src="../assets/k80.gif"border=0>
<a href="../html/kdic81.php?v=<?php echo $version; ?>"><img src="../assets/k81.gif"border=0>
<a href="../html/kdic82.php?v=<?php echo $version; ?>"><img src="../assets/k82.gif"border=0>
<a href="../html/kdic83.php?v=<?php echo $version; ?>"><img src="../assets/k83.gif"border=0>
<a href="../html/kdic84.php?v=<?php echo $version; ?>"><img src="../assets/k84.gif"border=0>
<a href="../html/kdic85.php?v=<?php echo $version; ?>"><img src="../assets/k85.gif"border=0>
<a href="../html/kdic86.php?v=<?php echo $version; ?>"><img src="../assets/k86.gif"border=0>
<a href="../html/kdic87.php?v=<?php echo $version; ?>"><img src="../assets/k87.gif"border=0>
<a href="../html/kdic88.php?v=<?php echo $version; ?>"><img src="../assets/k88.gif"border=0>
<a href="../html/kdic89.php?v=<?php echo $version; ?>"><img src="../assets/k89.gif"border=0>
<a href="../html/kdic90.php?v=<?php echo $version; ?>"><img src="../assets/k90.gif"border=0>
<a href="../html/kdic91.php?v=<?php echo $version; ?>"><img src="../assets/k91.gif"border=0>
<a href="../html/kdic92.php?v=<?php echo $version; ?>"><img src="../assets/k92.gif"border=0>
<a href="../html/kdic93.php?v=<?php echo $version; ?>"><img src="../assets/k93.gif"border=0>
<a href="../html/kdic94.php?v=<?php echo $version; ?>"><img src="../assets/k94.gif"border=0>
<a href="../html/kdic95.php?v=<?php echo $version; ?>"><img src="../assets/k95.gif"border=0>
<a href="../html/kdic96.php?v=<?php echo $version; ?>"><img src="../assets/k96.gif"border=0>
<a href="../html/kdic97.php?v=<?php echo $version; ?>"><img src="../assets/k97.gif"border=0>
<a href="../html/kdic98.php?v=<?php echo $version; ?>"><img src="../assets/k98.gif"border=0>
<a href="../html/kdic99.php?v=<?php echo $version; ?>"><img src="../assets/k99.gif"border=0>
<a href="../html/kdic100.php?v=<?php echo $version; ?>"><img src="../assets/k100.gif"border=0>
<a href="../html/kdic101.php?v=<?php echo $version; ?>"><img src="../assets/k101.gif"border=0>
<a href="../html/kdic102.php?v=<?php echo $version; ?>"><img src="../assets/k102.gif"border=0>
<a href="../html/kdic103.php?v=<?php echo $version; ?>"><img src="../assets/k103.gif"border=0>
<a href="../html/kdic104.php?v=<?php echo $version; ?>"><img src="../assets/k104.gif"border=0>
<a href="../html/kdic105.php?v=<?php echo $version; ?>"><img src="../assets/k105.gif"border=0>
<a href="../html/kdic106.php?v=<?php echo $version; ?>"><img src="../assets/k106.gif"border=0>
<a href="../html/kdic107.php?v=<?php echo $version; ?>"><img src="../assets/k107.gif"border=0>
<a href="../html/kdic108.php?v=<?php echo $version; ?>"><img src="../assets/k108.gif"border=0>
<a href="../html/kdic109.php?v=<?php echo $version; ?>"><img src="../assets/k109.gif"border=0>
<a href="../html/kdic110.php?v=<?php echo $version; ?>"><img src="../assets/k110.gif"border=0>
<a href="../html/kdic111.php?v=<?php echo $version; ?>"><img src="../assets/k111.gif"border=0>
<a href="../html/kdic112.php?v=<?php echo $version; ?>"><img src="../assets/k112.gif"border=0>
<a href="../html/kdic113.php?v=<?php echo $version; ?>"><img src="../assets/k113.gif"border=0>
<a href="../html/kdic114.php?v=<?php echo $version; ?>"><img src="../assets/k114.gif"border=0>
<a href="../html/kdic115.php?v=<?php echo $version; ?>"><img src="../assets/k115.gif"border=0>
<a href="../html/kdic116.php?v=<?php echo $version; ?>"><img src="../assets/k116.gif"border=0>
<a href="../html/kdic117.php?v=<?php echo $version; ?>"><img src="../assets/k117.gif"border=0>
<a href="../html/kdic118.php?v=<?php echo $version; ?>"><img src="../assets/k118.gif"border=0>
<a href="../html/kdic119.php?v=<?php echo $version; ?>"><img src="../assets/k119.gif"border=0>
<a href="../html/kdic120.php?v=<?php echo $version; ?>"><img src="../assets/k120.gif"border=0>
<a href="../html/kdic121.php?v=<?php echo $version; ?>"><img src="../assets/k121.gif"border=0>
<a href="../html/kdic122.php?v=<?php echo $version; ?>"><img src="../assets/k122.gif"border=0>
<a href="../html/kdic123.php?v=<?php echo $version; ?>"><img src="../assets/k123.gif"border=0>
<a href="../html/kdic124.php?v=<?php echo $version; ?>"><img src="../assets/k124.gif"border=0>
<a href="../html/kdic125.php?v=<?php echo $version; ?>"><img src="../assets/k125.gif"border=0>
<a href="../html/kdic126.php?v=<?php echo $version; ?>"><img src="../assets/k126.gif"border=0>
<a href="../html/kdic127.php?v=<?php echo $version; ?>"><img src="../assets/k127.gif"border=0>
<a href="../html/kdic128.php?v=<?php echo $version; ?>"><img src="../assets/k128.gif"border=0>
<a href="../html/kdic129.php?v=<?php echo $version; ?>"><img src="../assets/k129.gif"border=0>
<a href="../html/kdic130.php?v=<?php echo $version; ?>"><img src="../assets/k130.gif"border=0>
<a href="../html/kdic131.php?v=<?php echo $version; ?>"><img src="../assets/k131.gif"border=0>
<a href="../html/kdic132.php?v=<?php echo $version; ?>"><img src="../assets/k132.gif"border=0>
<a href="../html/kdic133.php?v=<?php echo $version; ?>"><img src="../assets/k133.gif"border=0>
<a href="../html/kdic134.php?v=<?php echo $version; ?>"><img src="../assets/k134.gif"border=0>
<a href="../html/kdic135.php?v=<?php echo $version; ?>"><img src="../assets/k135.gif"border=0>
<a href="../html/kdic136.php?v=<?php echo $version; ?>"><img src="../assets/k136.gif"border=0>
<a href="../html/kdic137.php?v=<?php echo $version; ?>"><img src="../assets/k137.gif"border=0>
<a href="../html/kdic138.php?v=<?php echo $version; ?>"><img src="../assets/k138.gif"border=0>
<a href="../html/kdic139.php?v=<?php echo $version; ?>"><img src="../assets/k139.gif"border=0>
<a href="../html/kdic140.php?v=<?php echo $version; ?>"><img src="../assets/k140.gif"border=0>
<a href="../html/kdic141.php?v=<?php echo $version; ?>"><img src="../assets/k141.gif"border=0>
<a href="../html/kdic142.php?v=<?php echo $version; ?>"><img src="../assets/k142.gif"border=0>
<a href="../html/kdic143.php?v=<?php echo $version; ?>"><img src="../assets/k143.gif"border=0>
<a href="../html/kdic144.php?v=<?php echo $version; ?>"><img src="../assets/k144.gif"border=0>
<a href="../html/kdic145.php?v=<?php echo $version; ?>"><img src="../assets/k145.gif"border=0>
<a href="../html/kdic146.php?v=<?php echo $version; ?>"><img src="../assets/k146.gif"border=0>
<a href="../html/kdic147.php?v=<?php echo $version; ?>"><img src="../assets/k147.gif"border=0>
<a href="../html/kdic148.php?v=<?php echo $version; ?>"><img src="../assets/k148.gif"border=0>
<a href="../html/kdic149.php?v=<?php echo $version; ?>"><img src="../assets/k149.gif"border=0>
<a href="../html/kdic150.php?v=<?php echo $version; ?>"><img src="../assets/k150.gif"border=0>
<a href="../html/kdic151.php?v=<?php echo $version; ?>"><img src="../assets/k151.gif"border=0>
<a href="../html/kdic152.php?v=<?php echo $version; ?>"><img src="../assets/k152.gif"border=0>
<a href="../html/kdic153.php?v=<?php echo $version; ?>"><img src="../assets/k153.gif"border=0>
<a href="../html/kdic154.php?v=<?php echo $version; ?>"><img src="../assets/k154.gif"border=0>
<a href="../html/kdic155.php?v=<?php echo $version; ?>"><img src="../assets/k155.gif"border=0>
<a href="../html/kdic156.php?v=<?php echo $version; ?>"><img src="../assets/k156.gif"border=0>
<a href="../html/kdic157.php?v=<?php echo $version; ?>"><img src="../assets/k157.gif"border=0>
<a href="../html/kdic158.php?v=<?php echo $version; ?>"><img src="../assets/k158.gif"border=0>
<a href="../html/kdic159.php?v=<?php echo $version; ?>"><img src="../assets/k159.gif"border=0>
<a href="../html/kdic160.php?v=<?php echo $version; ?>"><img src="../assets/k160.gif"border=0>
<a href="../html/kdic161.php?v=<?php echo $version; ?>"><img src="../assets/k161.gif"border=0>
<a href="../html/kdic162.php?v=<?php echo $version; ?>"><img src="../assets/k162.gif"border=0>
<a href="../html/kdic163.php?v=<?php echo $version; ?>"><img src="../assets/k163.gif"border=0>
<a href="../html/kdic164.php?v=<?php echo $version; ?>"><img src="../assets/k164.gif"border=0>
<a href="../html/kdic165.php?v=<?php echo $version; ?>"><img src="../assets/k165.gif"border=0>
<a href="../html/kdic166.php?v=<?php echo $version; ?>"><img src="../assets/k166.gif"border=0>
<a href="../html/kdic167.php?v=<?php echo $version; ?>"><img src="../assets/k167.gif"border=0>
<a href="../html/kdic168.php?v=<?php echo $version; ?>"><img src="../assets/k168.gif"border=0>
<a href="../html/kdic169.php?v=<?php echo $version; ?>"><img src="../assets/k169.gif"border=0>
<a href="../html/kdic170.php?v=<?php echo $version; ?>"><img src="../assets/k170.gif"border=0>
<a href="../html/kdic171.php?v=<?php echo $version; ?>"><img src="../assets/k171.gif"border=0>
<a href="../html/kdic172.php?v=<?php echo $version; ?>"><img src="../assets/k172.gif"border=0>
<a href="../html/kdic173.php?v=<?php echo $version; ?>"><img src="../assets/k173.gif"border=0>
<a href="../html/kdic174.php?v=<?php echo $version; ?>"><img src="../assets/k174.gif"border=0>
<a href="../html/kdic175.php?v=<?php echo $version; ?>"><img src="../assets/k175.gif"border=0>
<a href="../html/kdic176.php?v=<?php echo $version; ?>"><img src="../assets/k176.gif"border=0>
<a href="../html/kdic177.php?v=<?php echo $version; ?>"><img src="../assets/k177.gif"border=0>
<a href="../html/kdic178.php?v=<?php echo $version; ?>"><img src="../assets/k178.gif"border=0>
<a href="../html/kdic179.php?v=<?php echo $version; ?>"><img src="../assets/k179.gif"border=0>
<a href="../html/kdic180.php?v=<?php echo $version; ?>"><img src="../assets/k180.gif"border=0>
<a href="../html/kdic181.php?v=<?php echo $version; ?>"><img src="../assets/k181.gif"border=0>
<a href="../html/kdic182.php?v=<?php echo $version; ?>"><img src="../assets/k182.gif"border=0>
<a href="../html/kdic183.php?v=<?php echo $version; ?>"><img src="../assets/k183.gif"border=0>
<a href="../html/kdic184.php?v=<?php echo $version; ?>"><img src="../assets/k184.gif"border=0>
<a href="../html/kdic185.php?v=<?php echo $version; ?>"><img src="../assets/k185.gif"border=0>
<a href="../html/kdic186.php?v=<?php echo $version; ?>"><img src="../assets/k186.gif"border=0>
<a href="../html/kdic187.php?v=<?php echo $version; ?>"><img src="../assets/k187.gif"border=0>
<a href="../html/kdic188.php?v=<?php echo $version; ?>"><img src="../assets/k188.gif"border=0>
<a href="../html/kdic189.php?v=<?php echo $version; ?>"><img src="../assets/k189.gif"border=0>
<a href="../html/kdic190.php?v=<?php echo $version; ?>"><img src="../assets/k190.gif"border=0>
<a href="../html/kdic191.php?v=<?php echo $version; ?>"><img src="../assets/k191.gif"border=0>
<a href="../html/kdic192.php?v=<?php echo $version; ?>"><img src="../assets/k192.gif"border=0>
<a href="../html/kdic193.php?v=<?php echo $version; ?>"><img src="../assets/k193.gif"border=0>
<a href="../html/kdic194.php?v=<?php echo $version; ?>"><img src="../assets/k194.gif"border=0>
<a href="../html/kdic195.php?v=<?php echo $version; ?>"><img src="../assets/k195.gif"border=0>
<a href="../html/kdic196.php?v=<?php echo $version; ?>"><img src="../assets/k196.gif"border=0>
<a href="../html/kdic197.php?v=<?php echo $version; ?>"><img src="../assets/k197.gif"border=0>
<a href="../html/kdic198.php?v=<?php echo $version; ?>"><img src="../assets/k198.gif"border=0>
<a href="../html/kdic199.php?v=<?php echo $version; ?>"><img src="../assets/k199.gif"border=0>
<a href="../html/kdic200.php?v=<?php echo $version; ?>"><img src="../assets/k200.gif"border=0>
<a href="../html/kdic201.php?v=<?php echo $version; ?>"><img src="../assets/k201.gif"border=0>
<a href="../html/kdic202.php?v=<?php echo $version; ?>"><img src="../assets/k202.gif"border=0>
<a href="../html/kdic203.php?v=<?php echo $version; ?>"><img src="../assets/k203.gif"border=0>
<a href="../html/kdic204.php?v=<?php echo $version; ?>"><img src="../assets/k204.gif"border=0>
<a href="../html/kdic205.php?v=<?php echo $version; ?>"><img src="../assets/k205.gif"border=0>
<a href="../html/kdic206.php?v=<?php echo $version; ?>"><img src="../assets/k206.gif"border=0>
<a href="../html/kdic207.php?v=<?php echo $version; ?>"><img src="../assets/k207.gif"border=0>
<a href="../html/kdic208.php?v=<?php echo $version; ?>"><img src="../assets/k208.gif"border=0>
<a href="../html/kdic209.php?v=<?php echo $version; ?>"><img src="../assets/k209.gif"border=0>
<a href="../html/kdic210.php?v=<?php echo $version; ?>"><img src="../assets/k210.gif"border=0>
<a href="../html/kdic211.php?v=<?php echo $version; ?>"><img src="../assets/k211.gif"border=0>
<a href="../html/kdic212.php?v=<?php echo $version; ?>"><img src="../assets/k212.gif"border=0>
<a href="../html/kdic213.php?v=<?php echo $version; ?>"><img src="../assets/k213.gif"border=0>
<a href="../html/kdic214.php?v=<?php echo $version; ?>"><img src="../assets/k214.gif"border=0>
<a href="../html/kdic215.php?v=<?php echo $version; ?>"><img src="../assets/k215.gif"border=0>
<a href="../html/kdic216.php?v=<?php echo $version; ?>"><img src="../assets/k216.gif"border=0>
<a href="../html/kdic217.php?v=<?php echo $version; ?>"><img src="../assets/k217.gif"border=0>
<a href="../html/kdic218.php?v=<?php echo $version; ?>"><img src="../assets/k218.gif"border=0>
<a href="../html/kdic219.php?v=<?php echo $version; ?>"><img src="../assets/k219.gif"border=0>
<a href="../html/kdic220.php?v=<?php echo $version; ?>"><img src="../assets/k220.gif"border=0>
<a href="../html/kdic221.php?v=<?php echo $version; ?>"><img src="../assets/k221.gif"border=0>
<a href="../html/kdic222.php?v=<?php echo $version; ?>"><img src="../assets/k222.gif"border=0>
<a href="../html/kdic223.php?v=<?php echo $version; ?>"><img src="../assets/k223.gif"border=0>
<a href="../html/kdic224.php?v=<?php echo $version; ?>"><img src="../assets/k224.gif"border=0>
<a href="../html/kdic225.php?v=<?php echo $version; ?>"><img src="../assets/k225.gif"border=0>
<a href="../html/kdic226.php?v=<?php echo $version; ?>"><img src="../assets/k226.gif"border=0>
<a href="../html/kdic227.php?v=<?php echo $version; ?>"><img src="../assets/k227.gif"border=0>
<a href="../html/kdic228.php?v=<?php echo $version; ?>"><img src="../assets/k228.gif"border=0>
<a href="../html/kdic229.php?v=<?php echo $version; ?>"><img src="../assets/k229.gif"border=0>
<a href="../html/kdic230.php?v=<?php echo $version; ?>"><img src="../assets/k230.gif"border=0>
<a href="../html/kdic231.php?v=<?php echo $version; ?>"><img src="../assets/k231.gif"border=0>
<a href="../html/kdic232.php?v=<?php echo $version; ?>"><img src="../assets/k232.gif"border=0>
<a href="../html/kdic233.php?v=<?php echo $version; ?>"><img src="../assets/k233.gif"border=0>
<a href="../html/kdic234.php?v=<?php echo $version; ?>"><img src="../assets/k234.gif"border=0>
<a href="../html/kdic235.php?v=<?php echo $version; ?>"><img src="../assets/k235.gif"border=0>
<a href="../html/kdic236.php?v=<?php echo $version; ?>"><img src="../assets/k236.gif"border=0>
<a href="../html/kdic237.php?v=<?php echo $version; ?>"><img src="../assets/k237.gif"border=0>
<a href="../html/kdic238.php?v=<?php echo $version; ?>"><img src="../assets/k238.gif"border=0>
<a href="../html/kdic239.php?v=<?php echo $version; ?>"><img src="../assets/k239.gif"border=0>
<a href="../html/kdic240.php?v=<?php echo $version; ?>"><img src="../assets/k240.gif"border=0>
<a href="../html/kdic241.php?v=<?php echo $version; ?>"><img src="../assets/k241.gif"border=0>
<a href="../html/kdic242.php?v=<?php echo $version; ?>"><img src="../assets/k242.gif"border=0>
<a href="../html/kdic243.php?v=<?php echo $version; ?>"><img src="../assets/k243.gif"border=0>
<a href="../html/kdic244.php?v=<?php echo $version; ?>"><img src="../assets/k244.gif"border=0>
<a href="../html/kdic245.php?v=<?php echo $version; ?>"><img src="../assets/k245.gif"border=0>
<a href="../html/kdic246.php?v=<?php echo $version; ?>"><img src="../assets/k246.gif"border=0>
<a href="../html/kdic247.php?v=<?php echo $version; ?>"><img src="../assets/k247.gif"border=0>
<a href="../html/kdic248.php?v=<?php echo $version; ?>"><img src="../assets/k248.gif"border=0>
<a href="../html/kdic249.php?v=<?php echo $version; ?>"><img src="../assets/k249.gif"border=0>
<a href="../html/kdic250.php?v=<?php echo $version; ?>"><img src="../assets/k250.gif"border=0>
<a href="../html/kdic251.php?v=<?php echo $version; ?>"><img src="../assets/k251.gif"border=0>
<a href="../html/kdic252.php?v=<?php echo $version; ?>"><img src="../assets/k252.gif"border=0>
<a href="../html/kdic253.php?v=<?php echo $version; ?>"><img src="../assets/k253.gif"border=0>
<a href="../html/kdic254.php?v=<?php echo $version; ?>"><img src="../assets/k254.gif"border=0>
<a href="../html/kdic255.php?v=<?php echo $version; ?>"><img src="../assets/k255.gif"border=0>
<a href="../html/kdic256.php?v=<?php echo $version; ?>"><img src="../assets/k256.gif"border=0>
<a href="../html/kdic257.php?v=<?php echo $version; ?>"><img src="../assets/k257.gif"border=0>
<a href="../html/kdic258.php?v=<?php echo $version; ?>"><img src="../assets/k258.gif"border=0>
<a href="../html/kdic259.php?v=<?php echo $version; ?>"><img src="../assets/k259.gif"border=0>
<a href="../html/kdic260.php?v=<?php echo $version; ?>"><img src="../assets/k260.gif"border=0>
<a href="../html/kdic261.php?v=<?php echo $version; ?>"><img src="../assets/k261.gif"border=0>
<a href="../html/kdic262.php?v=<?php echo $version; ?>"><img src="../assets/k262.gif"border=0>
<a href="../html/kdic263.php?v=<?php echo $version; ?>"><img src="../assets/k263.gif"border=0>
<a href="../html/kdic264.php?v=<?php echo $version; ?>"><img src="../assets/k264.gif"border=0>
<a href="../html/kdic265.php?v=<?php echo $version; ?>"><img src="../assets/k265.gif"border=0>
<a href="../html/kdic266.php?v=<?php echo $version; ?>"><img src="../assets/k266.gif"border=0>
<a href="../html/kdic267.php?v=<?php echo $version; ?>"><img src="../assets/k267.gif"border=0>
<a href="../html/kdic268.php?v=<?php echo $version; ?>"><img src="../assets/k268.gif"border=0>
<a href="../html/kdic269.php?v=<?php echo $version; ?>"><img src="../assets/k269.gif"border=0>
<a href="../html/kdic270.php?v=<?php echo $version; ?>"><img src="../assets/k270.gif"border=0>
<a href="../html/kdic271.php?v=<?php echo $version; ?>"><img src="../assets/k271.gif"border=0>
<a href="../html/kdic272.php?v=<?php echo $version; ?>"><img src="../assets/k272.gif"border=0>
<a href="../html/kdic273.php?v=<?php echo $version; ?>"><img src="../assets/k273.gif"border=0>
<a href="../html/kdic274.php?v=<?php echo $version; ?>"><img src="../assets/k274.gif"border=0>
<a href="../html/kdic275.php?v=<?php echo $version; ?>"><img src="../assets/k275.gif"border=0>
<a href="../html/kdic276.php?v=<?php echo $version; ?>"><img src="../assets/k276.gif"border=0>
<a href="../html/kdic277.php?v=<?php echo $version; ?>"><img src="../assets/k277.gif"border=0>
<a href="../html/kdic278.php?v=<?php echo $version; ?>"><img src="../assets/k278.gif"border=0>
<a href="../html/kdic279.php?v=<?php echo $version; ?>"><img src="../assets/k279.gif"border=0>
<a href="../html/kdic280.php?v=<?php echo $version; ?>"><img src="../assets/k280.gif"border=0>
<a href="../html/kdic281.php?v=<?php echo $version; ?>"><img src="../assets/k281.gif"border=0>
<a href="../html/kdic282.php?v=<?php echo $version; ?>"><img src="../assets/k282.gif"border=0>
<a href="../html/kdic283.php?v=<?php echo $version; ?>"><img src="../assets/k283.gif"border=0>
<a href="../html/kdic284.php?v=<?php echo $version; ?>"><img src="../assets/k284.gif"border=0>
<a href="../html/kdic285.php?v=<?php echo $version; ?>"><img src="../assets/k285.gif"border=0>
<a href="../html/kdic286.php?v=<?php echo $version; ?>"><img src="../assets/k286.gif"border=0>
<a href="../html/kdic287.php?v=<?php echo $version; ?>"><img src="../assets/k287.gif"border=0>
<a href="../html/kdic288.php?v=<?php echo $version; ?>"><img src="../assets/k288.gif"border=0>
<a href="../html/kdic289.php?v=<?php echo $version; ?>"><img src="../assets/k289.gif"border=0>
<a href="../html/kdic290.php?v=<?php echo $version; ?>"><img src="../assets/k290.gif"border=0>
<a href="../html/kdic291.php?v=<?php echo $version; ?>"><img src="../assets/k291.gif"border=0>
<a href="../html/kdic292.php?v=<?php echo $version; ?>"><img src="../assets/k292.gif"border=0>
<a href="../html/kdic293.php?v=<?php echo $version; ?>"><img src="../assets/k293.gif"border=0>
<a href="../html/kdic294.php?v=<?php echo $version; ?>"><img src="../assets/k294.gif"border=0>
<a href="../html/kdic295.php?v=<?php echo $version; ?>"><img src="../assets/k295.gif"border=0>
<a href="../html/kdic296.php?v=<?php echo $version; ?>"><img src="../assets/k296.gif"border=0>
<a href="../html/kdic297.php?v=<?php echo $version; ?>"><img src="../assets/k297.gif"border=0>
<a href="../html/kdic298.php?v=<?php echo $version; ?>"><img src="../assets/k298.gif"border=0>
<a href="../html/kdic299.php?v=<?php echo $version; ?>"><img src="../assets/k299.gif"border=0>
<a href="../html/kdic300.php?v=<?php echo $version; ?>"><img src="../assets/k300.gif"border=0>
<a href="../html/kdic301.php?v=<?php echo $version; ?>"><img src="../assets/k301.gif"border=0>
<a href="../html/kdic302.php?v=<?php echo $version; ?>"><img src="../assets/k302.gif"border=0>
<a href="../html/kdic303.php?v=<?php echo $version; ?>"><img src="../assets/k303.gif"border=0>
<a href="../html/kdic304.php?v=<?php echo $version; ?>"><img src="../assets/k304.gif"border=0>
<a href="../html/kdic305.php?v=<?php echo $version; ?>"><img src="../assets/k305.gif"border=0>
<a href="../html/kdic306.php?v=<?php echo $version; ?>"><img src="../assets/k306.gif"border=0>
<a href="../html/kdic307.php?v=<?php echo $version; ?>"><img src="../assets/k307.gif"border=0>
<a href="../html/kdic308.php?v=<?php echo $version; ?>"><img src="../assets/k308.gif"border=0>
<a href="../html/kdic309.php?v=<?php echo $version; ?>"><img src="../assets/k309.gif"border=0>
<a href="../html/kdic310.php?v=<?php echo $version; ?>"><img src="../assets/k310.gif"border=0>
<a href="../html/kdic311.php?v=<?php echo $version; ?>"><img src="../assets/k311.gif"border=0>
<a href="../html/kdic312.php?v=<?php echo $version; ?>"><img src="../assets/k312.gif"border=0>
<a href="../html/kdic313.php?v=<?php echo $version; ?>"><img src="../assets/k313.gif"border=0>
<a href="../html/kdic314.php?v=<?php echo $version; ?>"><img src="../assets/k314.gif"border=0>
<a href="../html/kdic315.php?v=<?php echo $version; ?>"><img src="../assets/k315.gif"border=0>
<a href="../html/kdic316.php?v=<?php echo $version; ?>"><img src="../assets/k316.gif"border=0>
<a href="../html/kdic317.php?v=<?php echo $version; ?>"><img src="../assets/k317.gif"border=0>
<a href="../html/kdic318.php?v=<?php echo $version; ?>"><img src="../assets/k318.gif"border=0>
<a href="../html/kdic319.php?v=<?php echo $version; ?>"><img src="../assets/k319.gif"border=0>
<a href="../html/kdic320.php?v=<?php echo $version; ?>"><img src="../assets/k320.gif"border=0>
<a href="../html/kdic321.php?v=<?php echo $version; ?>"><img src="../assets/k321.gif"border=0>
<a href="../html/kdic322.php?v=<?php echo $version; ?>"><img src="../assets/k322.gif"border=0>
<a href="../html/kdic323.php?v=<?php echo $version; ?>"><img src="../assets/k323.gif"border=0>
<a href="../html/kdic324.php?v=<?php echo $version; ?>"><img src="../assets/k324.gif"border=0>
<a href="../html/kdic325.php?v=<?php echo $version; ?>"><img src="../assets/k325.gif"border=0>
<a href="../html/kdic326.php?v=<?php echo $version; ?>"><img src="../assets/k326.gif"border=0>
<a href="../html/kdic327.php?v=<?php echo $version; ?>"><img src="../assets/k327.gif"border=0>
<a href="../html/kdic328.php?v=<?php echo $version; ?>"><img src="../assets/k328.gif"border=0>
<a href="../html/kdic329.php?v=<?php echo $version; ?>"><img src="../assets/k329.gif"border=0>
<a href="../html/kdic330.php?v=<?php echo $version; ?>"><img src="../assets/k330.gif"border=0>
<a href="../html/kdic331.php?v=<?php echo $version; ?>"><img src="../assets/k331.gif"border=0>
<a href="../html/kdic332.php?v=<?php echo $version; ?>"><img src="../assets/k332.gif"border=0>
<a href="../html/kdic333.php?v=<?php echo $version; ?>"><img src="../assets/k333.gif"border=0>
<a href="../html/kdic334.php?v=<?php echo $version; ?>"><img src="../assets/k334.gif"border=0>
<a href="../html/kdic335.php?v=<?php echo $version; ?>"><img src="../assets/k335.gif"border=0>
<a href="../html/kdic336.php?v=<?php echo $version; ?>"><img src="../assets/k336.gif"border=0>
<a href="../html/kdic337.php?v=<?php echo $version; ?>"><img src="../assets/k337.gif"border=0>
<a href="../html/kdic338.php?v=<?php echo $version; ?>"><img src="../assets/k338.gif"border=0>
<a href="../html/kdic339.php?v=<?php echo $version; ?>"><img src="../assets/k339.gif"border=0>
<a href="../html/kdic340.php?v=<?php echo $version; ?>"><img src="../assets/k340.gif"border=0>
<a href="../html/kdic341.php?v=<?php echo $version; ?>"><img src="../assets/k341.gif"border=0>
<a href="../html/kdic342.php?v=<?php echo $version; ?>"><img src="../assets/k342.gif"border=0>
<a href="../html/kdic343.php?v=<?php echo $version; ?>"><img src="../assets/k343.gif"border=0>
<a href="../html/kdic344.php?v=<?php echo $version; ?>"><img src="../assets/k344.gif"border=0>
<a href="../html/kdic345.php?v=<?php echo $version; ?>"><img src="../assets/k345.gif"border=0>
<a href="../html/kdic346.php?v=<?php echo $version; ?>"><img src="../assets/k346.gif"border=0>
<a href="../html/kdic347.php?v=<?php echo $version; ?>"><img src="../assets/k347.gif"border=0>
<a href="../html/kdic348.php?v=<?php echo $version; ?>"><img src="../assets/k348.gif"border=0>
<a href="../html/kdic349.php?v=<?php echo $version; ?>"><img src="../assets/k349.gif"border=0>
<a href="../html/kdic350.php?v=<?php echo $version; ?>"><img src="../assets/k350.gif"border=0>
<a href="../html/kdic351.php?v=<?php echo $version; ?>"><img src="../assets/k351.gif"border=0>
<a href="../html/kdic352.php?v=<?php echo $version; ?>"><img src="../assets/k352.gif"border=0>
<a href="../html/kdic353.php?v=<?php echo $version; ?>"><img src="../assets/k353.gif"border=0>
<a href="../html/kdic354.php?v=<?php echo $version; ?>"><img src="../assets/k354.gif"border=0>
<a href="../html/kdic355.php?v=<?php echo $version; ?>"><img src="../assets/k355.gif"border=0>
<a href="../html/kdic356.php?v=<?php echo $version; ?>"><img src="../assets/k356.gif"border=0>
<a href="../html/kdic357.php?v=<?php echo $version; ?>"><img src="../assets/k357.gif"border=0>
<a href="../html/kdic358.php?v=<?php echo $version; ?>"><img src="../assets/k358.gif"border=0>
<a href="../html/kdic359.php?v=<?php echo $version; ?>"><img src="../assets/k359.gif"border=0>
<a href="../html/kdic360.php?v=<?php echo $version; ?>"><img src="../assets/k360.gif"border=0>
<a href="../html/kdic361.php?v=<?php echo $version; ?>"><img src="../assets/k361.gif"border=0>
<a href="../html/kdic362.php?v=<?php echo $version; ?>"><img src="../assets/k362.gif"border=0>
<a href="../html/kdic363.php?v=<?php echo $version; ?>"><img src="../assets/k363.gif"border=0>
<a href="../html/kdic364.php?v=<?php echo $version; ?>"><img src="../assets/k364.gif"border=0>
<a href="../html/kdic365.php?v=<?php echo $version; ?>"><img src="../assets/k365.gif"border=0>
<a href="../html/kdic366.php?v=<?php echo $version; ?>"><img src="../assets/k366.gif"border=0>
<a href="../html/kdic367.php?v=<?php echo $version; ?>"><img src="../assets/k367.gif"border=0>
<a href="../html/kdic368.php?v=<?php echo $version; ?>"><img src="../assets/k368.gif"border=0>
<a href="../html/kdic369.php?v=<?php echo $version; ?>"><img src="../assets/k369.gif"border=0>
<a href="../html/kdic370.php?v=<?php echo $version; ?>"><img src="../assets/k370.gif"border=0>
<a href="../html/kdic371.php?v=<?php echo $version; ?>"><img src="../assets/k371.gif"border=0>
<a href="../html/kdic372.php?v=<?php echo $version; ?>"><img src="../assets/k372.gif"border=0>
<a href="../html/kdic373.php?v=<?php echo $version; ?>"><img src="../assets/k373.gif"border=0>
<a href="../html/kdic374.php?v=<?php echo $version; ?>"><img src="../assets/k374.gif"border=0>
<a href="../html/kdic375.php?v=<?php echo $version; ?>"><img src="../assets/k375.gif"border=0>
<a href="../html/kdic376.php?v=<?php echo $version; ?>"><img src="../assets/k376.gif"border=0>
<a href="../html/kdic377.php?v=<?php echo $version; ?>"><img src="../assets/k377.gif"border=0>
<a href="../html/kdic378.php?v=<?php echo $version; ?>"><img src="../assets/k378.gif"border=0>
<a href="../html/kdic379.php?v=<?php echo $version; ?>"><img src="../assets/k379.gif"border=0>
<a href="../html/kdic380.php?v=<?php echo $version; ?>"><img src="../assets/k380.gif"border=0>
<a href="../html/kdic381.php?v=<?php echo $version; ?>"><img src="../assets/k381.gif"border=0>
<a href="../html/kdic382.php?v=<?php echo $version; ?>"><img src="../assets/k382.gif"border=0>
<a href="../html/kdic383.php?v=<?php echo $version; ?>"><img src="../assets/k383.gif"border=0>
<a href="../html/kdic384.php?v=<?php echo $version; ?>"><img src="../assets/k384.gif"border=0>
<a href="../html/kdic385.php?v=<?php echo $version; ?>"><img src="../assets/k385.gif"border=0>
<a href="../html/kdic386.php?v=<?php echo $version; ?>"><img src="../assets/k386.gif"border=0>
<a href="../html/kdic387.php?v=<?php echo $version; ?>"><img src="../assets/k387.gif"border=0>
<a href="../html/kdic388.php?v=<?php echo $version; ?>"><img src="../assets/k388.gif"border=0>
<a href="../html/kdic389.php?v=<?php echo $version; ?>"><img src="../assets/k389.gif"border=0>
<a href="../html/kdic390.php?v=<?php echo $version; ?>"><img src="../assets/k390.gif"border=0>
<a href="../html/kdic391.php?v=<?php echo $version; ?>"><img src="../assets/k391.gif"border=0>
<a href="../html/kdic392.php?v=<?php echo $version; ?>"><img src="../assets/k392.gif"border=0>
<a href="../html/kdic393.php?v=<?php echo $version; ?>"><img src="../assets/k393.gif"border=0>
<a href="../html/kdic394.php?v=<?php echo $version; ?>"><img src="../assets/k394.gif"border=0>
<a href="../html/kdic395.php?v=<?php echo $version; ?>"><img src="../assets/k395.gif"border=0>
<a href="../html/kdic396.php?v=<?php echo $version; ?>"><img src="../assets/k396.gif"border=0>
<a href="../html/kdic397.php?v=<?php echo $version; ?>"><img src="../assets/k397.gif"border=0>
<a href="../html/kdic398.php?v=<?php echo $version; ?>"><img src="../assets/k398.gif"border=0>
<a href="../html/kdic399.php?v=<?php echo $version; ?>"><img src="../assets/k399.gif"border=0>
<a href="../html/kdic400.php?v=<?php echo $version; ?>"><img src="../assets/k400.gif"border=0>
<a href="../html/kdic401.php?v=<?php echo $version; ?>"><img src="../assets/k401.gif"border=0>
<a href="../html/kdic402.php?v=<?php echo $version; ?>"><img src="../assets/k402.gif"border=0>
</center><?php include '../bgsound.php'; ?>

</src><p align="center"><table>
<th><a href="../html/table.php?v=<?php echo $version; ?>"><img src="../assets/alphabet.gif" border=0></a>
<th><a href="../html/13a.php?v=<?php echo $version; ?>"><img src="../assets/arrow-left.png"><th></a>
<th><a href="../html/14.php?v=<?php echo $version; ?>"><img src="../assets/arrow-right.png"></a></table>
</p>
</tr>
<?php include '../footer.php'; ?>
</body>

</html>

